language: r
cache: packages
latex: false

r_packages:
  - covr

install:
  - R -e 'devtools::install_github("stephens999/ashr", upgrade="never", force=TRUE)'

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
